title: RLST210 - Hinduism
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/hinduismdemo" # the subpath of your site, e.g. /demo
url: "http://rlst210.online" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Hinduism, Spring 2018
author-img: mainhall.jpg
about-author: This is the webpage for Connie Kassor's Spring 2018 Hinduism course at Lawrence Unviersity. Here is where you'll find the course schedule, documents, and access our course blog.
email: constance.e.kassor@lawrence.edu


# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 12
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
