title: RLST210 - Hinduism
description: > # this means to ignore newlines until "baseurl:"
  Hinduism at Lawrence University, Spring 2018. Connie Kassor
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /demo
url: "http://rlst210.online" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Hinduism, Spring 2018
author-img: mainhall.jpg
about-author: This is the webpage for Connie Kassor's Spring 2018 Hinduism course at Lawrence Unviersity. Here is where you'll find all of the information, readings, and resources relevant to the course.

email: constance.e.kassor@lawrence.edu


# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 15
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
